### ISSUE TITLE
Vitrum II EU satellite wireless

### ISSUE THREAD

**Issue by GASNAG** [diamond5170/com.vitrum#5]
All the other EU Vitrum work very well but for the II EU satellite wireless I can't add on my HOMEY, it can't recognize like VITRUM but like generic Z-Wave.

Thanks for all

**Comment by GASNAG** [comment]
More information:

Davice ID 44
Manufacturer ID 266
Product Type ID 5120
Product ID 25088

**Comment by SmartHaven** [comment]
Fixed

**Comment by GASNAG** [comment]
The problem persist!!!

**Comment by SmartHaven** [comment]
New version (1.0.5) will be available only after approve.

**Comment by GASNAG** [comment]
Thanks, please send me a message when it’s approved

Bye

GA

Inviato da iPhone

> Il giorno 23 giu 2019, alle ore 10:09, Dmitriy Ponomarev <notifications@github.com> ha scritto:
> 
> New version (1.0.5) will be available only after approve.
>

**Comment by SmartHaven** [comment]
Approved
